<a href="https://colab.research.google.com/github/DebjitHore/PyTorchLearning/blob/main/00_PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


###Intro to Tensors

In [2]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [3]:
sc.ndim

0

In [4]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [5]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [6]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [7]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
mt.ndim

2

In [9]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))

###Creating random tensors

In [10]:
random= torch.rand(2,2,3)
print(random.type)
print(random)

<built-in method type of Tensor object at 0x7be770299070>
tensor([[[0.9263, 0.0473, 0.6879],
         [0.3528, 0.6129, 0.0463]],

        [[0.9154, 0.5769, 0.1462],
         [0.5028, 0.6882, 0.1394]]])


**Zeros and Ones Tensors**

In [11]:
X=torch.zeros(2,2,3)
Y=torch.ones(2,2,3)
print(X), print(Y)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


(None, None)

In [12]:
Y_new=torch.rand_like(Y) #generate a tensor that is dimensionally same as Y, but with random numbers
print(Y_new)

tensor([[[0.1479, 0.7369, 0.4246],
         [0.5557, 0.8180, 0.8313]],

        [[0.1482, 0.7714, 0.7304],
         [0.0023, 0.8292, 0.2367]]])


In [13]:
#random image sized tensor
random_image_size_tensor=  torch.rand(224,224,3) #height, width of pixels and colour channels (R,G,B)

In [14]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [15]:
random_image_size_tensor.dtype

torch.float32

In [16]:
rangedTensor=torch.arange(start=1, end=1000, step=20.5)
rangedTensor

tensor([  1.0000,  21.5000,  42.0000,  62.5000,  83.0000, 103.5000, 124.0000,
        144.5000, 165.0000, 185.5000, 206.0000, 226.5000, 247.0000, 267.5000,
        288.0000, 308.5000, 329.0000, 349.5000, 370.0000, 390.5000, 411.0000,
        431.5000, 452.0000, 472.5000, 493.0000, 513.5000, 534.0000, 554.5000,
        575.0000, 595.5000, 616.0000, 636.5000, 657.0000, 677.5000, 698.0000,
        718.5000, 739.0000, 759.5000, 780.0000, 800.5000, 821.0000, 841.5000,
        862.0000, 882.5000, 903.0000, 923.5000, 944.0000, 964.5000, 985.0000])

In [17]:
rangedZeroTensor=torch.rand_like(rangedTensor) #random tensor same size as rangedTensor
rangedZeroTensor

tensor([0.1992, 0.4053, 0.6076, 0.5539, 0.8046, 0.8928, 0.2806, 0.1061, 0.4141,
        0.1918, 0.2646, 0.4463, 0.0673, 0.6199, 0.9822, 0.6910, 0.2686, 0.6998,
        0.7392, 0.1179, 0.5117, 0.2906, 0.4957, 0.7759, 0.4761, 0.5689, 0.0455,
        0.2695, 0.2732, 0.0299, 0.7957, 0.2821, 0.7188, 0.2235, 0.8049, 0.6142,
        0.0865, 0.8631, 0.6879, 0.4394, 0.7777, 0.0191, 0.8445, 0.1529, 0.0013,
        0.4440, 0.6403, 0.2430, 0.3491])

### Tensor Datatypes

In [18]:
rand_tensor= torch.rand_like(rangedZeroTensor, dtype=None, device=None,requires_grad=False)
#dtype is float32 by default, single precision
#device= whether the tensor lives on cpu or gpu
#requires_grad= tracks gradient

In [19]:
rand_tensor

tensor([0.5108, 0.6976, 0.0965, 0.2907, 0.6718, 0.1429, 0.4069, 0.8884, 0.6224,
        0.0999, 0.7067, 0.7907, 0.2081, 0.6437, 0.0702, 0.3979, 0.8100, 0.2161,
        0.2906, 0.7569, 0.2970, 0.0831, 0.5690, 0.6670, 0.4093, 0.8404, 0.7066,
        0.8697, 0.3483, 0.4450, 0.9467, 0.3633, 0.1894, 0.6904, 0.9280, 0.0165,
        0.0191, 0.6950, 0.6354, 0.2687, 0.6206, 0.6432, 0.7025, 0.5976, 0.6863,
        0.6189, 0.2671, 0.4440, 0.7112])

**Tensors need to have compatible data type, shape and device to be operable**
1. Device type refers to the location of the tensor, whether it lives on cpu or gpu (device="cuda")

### Getting tensor attributes & tensor operations

1. Attributes\
  &emsp; tensorName.dtype \
  &emsp; tensorName.shape \
  &emsp; tensorName.size() \
  &emsp; tensorName.device \


2. Tensor operations \
&emsp; Addition \
&emsp; Substraction \
&emsp; Multiplication (element-wise) \
&emsp; Division \
&emsp; Matrix multiplication \


In [20]:
tensor_DJ= torch.arange(start=1, end=9, step=3, dtype=torch.float32)
tensor_DJ, tensor_DJ.dtype

(tensor([1., 4., 7.]), torch.float32)

In [21]:
tensor_DJ+10

tensor([11., 14., 17.])

In [22]:
tensor_DJ*10

tensor([10., 40., 70.])

In [23]:
tensor_DJ-10

tensor([-9., -6., -3.])

In [24]:
torch.mul(tensor_DJ,10) #pytorch operator for element-wise matrix multiplication

tensor([10., 40., 70.])

In [25]:
#matrix multiplication
#element-wise
tensor_DJNew=torch.rand_like(tensor_DJ,dtype=torch.float32)
print(tensor_DJNew)
elemMul = tensor_DJ*tensor_DJNew
elemMul

tensor([0.3378, 0.8515, 0.6577])


tensor([0.3378, 3.4062, 4.6039])

In [26]:
matrixmul=torch.matmul(tensor_DJNew, tensor_DJ)
matrixmul

tensor(8.3479)

Rules for matrix mutliplication:

1. **Inner dimensions** must match:\
&emsp; (3,2) @ (3,2) won't work \
&emsp; (2,3) @ (3,2) will work
2. **Outer dimensions** will be the shape of resulting matrix



### Errors in deep learning : shape error for tensors

In [32]:
torch.mm (torch.rand(2,3), torch.rand(3,2)) #mm is an alias for matmul

tensor([[1.1048, 0.3425],
        [0.9820, 0.5976]])

#### Transposing a tensor

In [36]:
#transpose of a tensor
B=torch.rand(3,4)
B, B.shape

(tensor([[0.4466, 0.1268, 0.2119, 0.3074],
         [0.8523, 0.3562, 0.0575, 0.2586],
         [0.2478, 0.0555, 0.4182, 0.5173]]),
 torch.Size([3, 4]))

In [38]:
A=B.T
A, A.shape

(tensor([[0.4466, 0.8523, 0.2478],
         [0.1268, 0.3562, 0.0555],
         [0.2119, 0.0575, 0.4182],
         [0.3074, 0.2586, 0.5173]]),
 torch.Size([4, 3]))

#### Tensor aggregation

`Finding the min, max, sum etc `

In [50]:
x=torch.arange(1,101,10, dtype=torch.float32)
x

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [51]:
torch.min(x), x.min()

(tensor(1.), tensor(1.))

In [52]:
torch.max(x), x.max()

(tensor(91.), tensor(91.))

`torch.mean(x) needs float32 type`

In [53]:
torch.mean(x), x.mean()

(tensor(46.), tensor(46.))

In [54]:
torch.sum(x), x.sum()

(tensor(460.), tensor(460.))

`Finding the positional min and max`

In [55]:
x.argmin() #position of minimum value in tensor x

tensor(0)

In [56]:
x.argmax()

tensor(9)