<a href="https://colab.research.google.com/github/DebjitHore/PyTorchLearning/blob/main/00_PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Intro to Tensors

In [2]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [3]:
sc.ndim

0

In [4]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [5]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [6]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [7]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
mt.ndim

2

In [9]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))

##Creating random tensors

In [11]:
random= torch.rand(2,2,3)
print(random.type)
print(random)

<built-in method type of Tensor object at 0x7b99aa8fa7b0>
tensor([[[0.4577, 0.5189, 0.0930],
         [0.0085, 0.6973, 0.7731]],

        [[0.5621, 0.0557, 0.7298],
         [0.9105, 0.8901, 0.0717]]])


**Zeros and Ones Tensors**

In [12]:
X=torch.zeros(2,2,3)
Y=torch.ones(2,2,3)
print(X), print(Y)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


(None, None)

In [14]:
Y_new=torch.rand_like(Y) #generate a tensor that is dimensionally same as Y, but with random numbers
print(Y_new)

tensor([[[0.4920, 0.5167, 0.8620],
         [0.7028, 0.3015, 0.5655]],

        [[0.2641, 0.0164, 0.6690],
         [0.2030, 0.3906, 0.4328]]])


In [15]:
#random image sized tensor
random_image_size_tensor=  torch.rand(224,224,3) #height, width of pixels and colour channels (R,G,B)

In [17]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [18]:
random_image_size_tensor.dtype

torch.float32

In [23]:
rangedTensor=torch.arange(start=1, end=1000, step=20.5)
rangedTensor

tensor([  1.0000,  21.5000,  42.0000,  62.5000,  83.0000, 103.5000, 124.0000,
        144.5000, 165.0000, 185.5000, 206.0000, 226.5000, 247.0000, 267.5000,
        288.0000, 308.5000, 329.0000, 349.5000, 370.0000, 390.5000, 411.0000,
        431.5000, 452.0000, 472.5000, 493.0000, 513.5000, 534.0000, 554.5000,
        575.0000, 595.5000, 616.0000, 636.5000, 657.0000, 677.5000, 698.0000,
        718.5000, 739.0000, 759.5000, 780.0000, 800.5000, 821.0000, 841.5000,
        862.0000, 882.5000, 903.0000, 923.5000, 944.0000, 964.5000, 985.0000])

In [25]:
rangedZeroTensor=torch.rand_like(rangedTensor) #random tensor same size as rangedTensor
rangedZeroTensor

tensor([0.3086, 0.6793, 0.9506, 0.3280, 0.9783, 0.5488, 0.0927, 0.2589, 0.1785,
        0.7209, 0.3011, 0.7165, 0.2593, 0.2163, 0.8307, 0.2624, 0.8983, 0.2387,
        0.1500, 0.9865, 0.9986, 0.2653, 0.8927, 0.1099, 0.1225, 0.9585, 0.6853,
        0.3651, 0.5895, 0.4392, 0.8661, 0.4513, 0.4499, 0.5969, 0.8334, 0.6241,
        0.0153, 0.0928, 0.5064, 0.6799, 0.9298, 0.8356, 0.9133, 0.2541, 0.5805,
        0.7899, 0.6193, 0.0071, 0.6531])