<a href="https://colab.research.google.com/github/DebjitHore/PyTorchLearning/blob/main/00_PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


###Intro to Tensors

In [2]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [3]:
sc.ndim

0

In [4]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [5]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [6]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [7]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
mt.ndim

2

In [9]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))

###Creating random tensors

In [10]:
random= torch.rand(2,2,3)
print(random.type)
print(random)

<built-in method type of Tensor object at 0x7cd39f934770>
tensor([[[0.1648, 0.7216, 0.9617],
         [0.1969, 0.7728, 0.8054]],

        [[0.7262, 0.4950, 0.7125],
         [0.3178, 0.1447, 0.1512]]])


**Zeros and Ones Tensors**

In [11]:
X=torch.zeros(2,2,3)
Y=torch.ones(2,2,3)
print(X), print(Y)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


(None, None)

In [12]:
Y_new=torch.rand_like(Y) #generate a tensor that is dimensionally same as Y, but with random numbers
print(Y_new)

tensor([[[0.8612, 0.4301, 0.0934],
         [0.4786, 0.8401, 0.0177]],

        [[0.4146, 0.5955, 0.9851],
         [0.8911, 0.6326, 0.9062]]])


In [13]:
#random image sized tensor
random_image_size_tensor=  torch.rand(224,224,3) #height, width of pixels and colour channels (R,G,B)

In [14]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [15]:
random_image_size_tensor.dtype

torch.float32

In [16]:
rangedTensor=torch.arange(start=1, end=1000, step=20.5)
rangedTensor

tensor([  1.0000,  21.5000,  42.0000,  62.5000,  83.0000, 103.5000, 124.0000,
        144.5000, 165.0000, 185.5000, 206.0000, 226.5000, 247.0000, 267.5000,
        288.0000, 308.5000, 329.0000, 349.5000, 370.0000, 390.5000, 411.0000,
        431.5000, 452.0000, 472.5000, 493.0000, 513.5000, 534.0000, 554.5000,
        575.0000, 595.5000, 616.0000, 636.5000, 657.0000, 677.5000, 698.0000,
        718.5000, 739.0000, 759.5000, 780.0000, 800.5000, 821.0000, 841.5000,
        862.0000, 882.5000, 903.0000, 923.5000, 944.0000, 964.5000, 985.0000])

In [17]:
rangedZeroTensor=torch.rand_like(rangedTensor) #random tensor same size as rangedTensor
rangedZeroTensor

tensor([0.5695, 0.7562, 0.4214, 0.5401, 0.3786, 0.0521, 0.3048, 0.0238, 0.1752,
        0.3731, 0.3279, 0.6502, 0.3565, 0.6362, 0.1966, 0.4045, 0.9027, 0.3352,
        0.0995, 0.6346, 0.9118, 0.7733, 0.5715, 0.5045, 0.9220, 0.5389, 0.2307,
        0.4273, 0.4865, 0.5145, 0.4769, 0.3482, 0.3499, 0.3773, 0.3277, 0.3697,
        0.5249, 0.6805, 0.8093, 0.5438, 0.8957, 0.7670, 0.6625, 0.1276, 0.7654,
        0.1353, 0.3289, 0.0304, 0.4573])

### Tensor Datatypes

In [18]:
rand_tensor= torch.rand_like(rangedZeroTensor, dtype=None, device=None,requires_grad=False)
#dtype is float32 by default, single precision
#device= whether the tensor lives on cpu or gpu
#requires_grad= tracks gradient

In [19]:
rand_tensor

tensor([0.4155, 0.9230, 0.7706, 0.7794, 0.8923, 0.2266, 0.1967, 0.6955, 0.7775,
        0.8840, 0.1570, 0.7154, 0.5777, 0.1492, 0.9609, 0.6373, 0.4143, 0.3953,
        0.3595, 0.7342, 0.8516, 0.5479, 0.2759, 0.7542, 0.5722, 0.9454, 0.8856,
        0.5142, 0.6269, 0.0420, 0.1058, 0.2148, 0.9829, 0.4290, 0.6859, 0.0719,
        0.3669, 0.1645, 0.9358, 0.3050, 0.3624, 0.8456, 0.2621, 0.1377, 0.1160,
        0.6779, 0.2735, 0.2602, 0.1683])

**Tensors need to have compatible data type, shape and device to be operable**
1. Device type refers to the location of the tensor, whether it lives on cpu or gpu (device="cuda")

### Getting tensor attributes & tensor operations

1. Attributes\
  &emsp; tensorName.dtype \
  &emsp; tensorName.shape \
  &emsp; tensorName.size() \
  &emsp; tensorName.device \


2. Tensor operations \
&emsp; Addition \
&emsp; Substraction \
&emsp; Multiplication (element-wise) \
&emsp; Division \
&emsp; Matrix multiplication \


In [20]:
tensor_DJ= torch.arange(start=1, end=9, step=3, dtype=torch.float32)
tensor_DJ, tensor_DJ.dtype

(tensor([1., 4., 7.]), torch.float32)

In [21]:
tensor_DJ+10

tensor([11., 14., 17.])

In [22]:
tensor_DJ*10

tensor([10., 40., 70.])

In [23]:
tensor_DJ-10

tensor([-9., -6., -3.])

In [24]:
torch.mul(tensor_DJ,10) #pytorch operator for element-wise matrix multiplication

tensor([10., 40., 70.])

In [25]:
#matrix multiplication
#element-wise
tensor_DJNew=torch.rand_like(tensor_DJ,dtype=torch.float32)
print(tensor_DJNew)
elemMul = tensor_DJ*tensor_DJNew
elemMul

tensor([0.3997, 0.4341, 0.1411])


tensor([0.3997, 1.7366, 0.9878])

In [26]:
matrixmul=torch.matmul(tensor_DJNew, tensor_DJ)
matrixmul

tensor(3.1241)

Rules for matrix mutliplication:

1. **Inner dimensions** must match:\
&emsp; (3,2) @ (3,2) won't work \
&emsp; (2,3) @ (3,2) will work
2. **Outer dimensions** will be the shape of resulting matrix



### Errors in deep learning : shape error for tensors

In [27]:
torch.mm (torch.rand(2,3), torch.rand(3,2)) #mm is an alias for matmul

tensor([[0.4806, 0.8087],
        [0.9839, 1.0896]])

#### Transposing a tensor

In [28]:
#transpose of a tensor
B=torch.rand(3,4)
B, B.shape

(tensor([[0.3238, 0.4594, 0.9440, 0.3163],
         [0.1705, 0.4135, 0.2619, 0.5009],
         [0.8735, 0.3912, 0.0827, 0.9566]]),
 torch.Size([3, 4]))

In [29]:
A=B.T
A, A.shape

(tensor([[0.3238, 0.1705, 0.8735],
         [0.4594, 0.4135, 0.3912],
         [0.9440, 0.2619, 0.0827],
         [0.3163, 0.5009, 0.9566]]),
 torch.Size([4, 3]))

#### Tensor aggregation

`Finding the min, max, sum etc `

In [30]:
x=torch.arange(1,101,10, dtype=torch.float32)
x

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [31]:
torch.min(x), x.min()

(tensor(1.), tensor(1.))

In [32]:
torch.max(x), x.max()

(tensor(91.), tensor(91.))

`torch.mean(x) needs float32 type`

In [33]:
torch.mean(x), x.mean()

(tensor(46.), tensor(46.))

In [34]:
torch.sum(x), x.sum()

(tensor(460.), tensor(460.))

`Finding the positional min and max`

In [35]:
x.argmin() #position of minimum value in tensor x

tensor(0)

In [36]:
x.argmax()

tensor(9)

`Reshaping and stacking tensors` \
1. `Reshaping` - reshapes input tensor to defined shape
2. `View` - Return a view of input tensor of certain shape but keep same memory as parent tensor
3. `Stack` - combine tensors on top of each other (vstack) or side by side (hstack)
4. `Squeeze` - remove all '1' dimensions from a tensor
5. `Unsqueeze` - adds a '1' dimensions to target tensor
6. `Permute` - Return a view of input tensor with dimensions swapped in a certain way

In [44]:
import torch as t
x=t.arange(0,10)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [42]:
#reshape
#x_reshaped = x.reshape(1,10)
#x_reshaped = x.reshape(10,1)
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]))

`x` and `z` share the same memory location therefore any change made to `z` will reflect in `x`

In [43]:
#change the view
z= x.view(10,1)
z, z.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [50]:
#stacking
x_stacked = t.stack((x,x,x,x), dim=0) #vertical stacking
print(x_stacked, x_stacked.shape)
x_stacked_horizontal = t.stack((x,x,x,x), dim=1)
print(x_stacked_horizontal, x_stacked_horizontal.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([4, 10])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]]) torch.Size([10, 4])


In [52]:
#squeezing and unsqueezing
x_reshaped_new=x.reshape(1,10)
x_reshaped_new,x_reshaped_new.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [55]:
x_reshaped_new.squeeze(), x_reshaped_new.squeeze().shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [60]:
x_reshaped_new.unsqueeze(dim=1), x_reshaped_new.unsqueeze(dim=1).shape

(tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 10]))

`permuting`

In [65]:
y=t.rand(2,3,3)
print(y, y.shape)
y_p=t.permute(y,(2,1,0))
print(y_p, y_p.shape)


tensor([[[0.4902, 0.8068, 0.3523],
         [0.2612, 0.0463, 0.3315],
         [0.4212, 0.3154, 0.2519]],

        [[0.3056, 0.9239, 0.9513],
         [0.3787, 0.0323, 0.8476],
         [0.5996, 0.0013, 0.2974]]]) torch.Size([2, 3, 3])
tensor([[[0.4902, 0.3056],
         [0.2612, 0.3787],
         [0.4212, 0.5996]],

        [[0.8068, 0.9239],
         [0.0463, 0.0323],
         [0.3154, 0.0013]],

        [[0.3523, 0.9513],
         [0.3315, 0.8476],
         [0.2519, 0.2974]]]) torch.Size([3, 3, 2])


`Indexing` -  Selecting data from Tensor

In [75]:
z=t.arange(1,19).reshape(2,3,3)
z, z.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [76]:
z[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
z[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [84]:
z[0, 0], z[0, 0:2]

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

`semi-colon` get all values

In [88]:
z[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])