**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/ 
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


**Intro to Tensors**

In [11]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [13]:
sc.ndim 

0

In [15]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [25]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [26]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [28]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
mt.ndim

2

In [32]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))