<a href="https://colab.research.google.com/github/DebjitHore/PyTorchLearning/blob/main/00_PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


###Intro to Tensors

In [2]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [3]:
sc.ndim

0

In [4]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [5]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [6]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [7]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
mt.ndim

2

In [9]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))

###Creating random tensors

In [10]:
random= torch.rand(2,2,3)
print(random.type)
print(random)

<built-in method type of Tensor object at 0x7e01e2689fd0>
tensor([[[0.4416, 0.9899, 0.9019],
         [0.8008, 0.1350, 0.5391]],

        [[0.6159, 0.6394, 0.8690],
         [0.9173, 0.6101, 0.7036]]])


**Zeros and Ones Tensors**

In [11]:
X=torch.zeros(2,2,3)
Y=torch.ones(2,2,3)
print(X), print(Y)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


(None, None)

In [12]:
Y_new=torch.rand_like(Y) #generate a tensor that is dimensionally same as Y, but with random numbers
print(Y_new)

tensor([[[0.6555, 0.4009, 0.3696],
         [0.9350, 0.7967, 0.7897]],

        [[0.9828, 0.6324, 0.3462],
         [0.0861, 0.8346, 0.5477]]])


In [13]:
#random image sized tensor
random_image_size_tensor=  torch.rand(224,224,3) #height, width of pixels and colour channels (R,G,B)

In [14]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [15]:
random_image_size_tensor.dtype

torch.float32

In [16]:
rangedTensor=torch.arange(start=1, end=1000, step=20.5)
rangedTensor

tensor([  1.0000,  21.5000,  42.0000,  62.5000,  83.0000, 103.5000, 124.0000,
        144.5000, 165.0000, 185.5000, 206.0000, 226.5000, 247.0000, 267.5000,
        288.0000, 308.5000, 329.0000, 349.5000, 370.0000, 390.5000, 411.0000,
        431.5000, 452.0000, 472.5000, 493.0000, 513.5000, 534.0000, 554.5000,
        575.0000, 595.5000, 616.0000, 636.5000, 657.0000, 677.5000, 698.0000,
        718.5000, 739.0000, 759.5000, 780.0000, 800.5000, 821.0000, 841.5000,
        862.0000, 882.5000, 903.0000, 923.5000, 944.0000, 964.5000, 985.0000])

In [17]:
rangedZeroTensor=torch.rand_like(rangedTensor) #random tensor same size as rangedTensor
rangedZeroTensor

tensor([0.0768, 0.3267, 0.1941, 0.5371, 0.7853, 0.8586, 0.4541, 0.0544, 0.7397,
        0.8517, 0.1461, 0.6371, 0.4870, 0.8552, 0.1418, 0.1063, 0.6086, 0.1107,
        0.3218, 0.3586, 0.8407, 0.0854, 0.4381, 0.8554, 0.2647, 0.3267, 0.5944,
        0.2131, 0.0536, 0.1616, 0.3251, 0.7715, 0.8984, 0.0947, 0.5275, 0.0667,
        0.0341, 0.1318, 0.7320, 0.8161, 0.9199, 0.6349, 0.4697, 0.0951, 0.6421,
        0.2942, 0.8795, 0.6570, 0.4751])

### Tensor Datatypes

In [22]:
rand_tensor= torch.rand_like(rangedZeroTensor, dtype=None, device=None,requires_grad=False)
#dtype is float32 by default, single precision
#device= whether the tensor lives on cpu or gpu
#requires_grad= tracks gradient

In [23]:
rand_tensor

tensor([0.6743, 0.6095, 0.0899, 0.8231, 0.4197, 0.6801, 0.3568, 0.6458, 0.8310,
        0.4637, 0.0154, 0.2085, 0.5712, 0.3440, 0.0413, 0.9234, 0.7110, 0.8060,
        0.6561, 0.3513, 0.5201, 0.2669, 0.9951, 0.5425, 0.5897, 0.3969, 0.5193,
        0.5961, 0.4573, 0.3105, 0.8083, 0.1961, 0.7242, 0.6254, 0.2585, 0.4664,
        0.6653, 0.1367, 0.8238, 0.7655, 0.5328, 0.8936, 0.8760, 0.5777, 0.8220,
        0.2803, 0.0903, 0.4393, 0.8875])

**Tensors need to have compatible data type, shape and device to be operable**
1. Device type refers to the location of the tensor, whether it lives on cpu or gpu (device="cuda")

### Getting tensor attributes & tensor operations

1. Attributes\
  &emsp; tensorName.dtype \
  &emsp; tensorName.shape \
  &emsp; tensorName.size() \
  &emsp; tensorName.device \


2. Tensor operations \
&emsp; Addition \
&emsp; Substraction \
&emsp; Multiplication (element-wise) \
&emsp; Division \
&emsp; Matrix multiplication \


In [46]:
tensor_DJ= torch.arange(start=1, end=9, step=3, dtype=torch.float32)
tensor_DJ, tensor_DJ.dtype

(tensor([1., 4., 7.]), torch.float32)

In [47]:
tensor_DJ+10

tensor([11., 14., 17.])

In [48]:
tensor_DJ*10

tensor([10., 40., 70.])

In [49]:
tensor_DJ-10

tensor([-9., -6., -3.])

In [50]:
torch.mul(tensor_DJ,10) #pytorch operator for element-wise matrix multiplication

tensor([10., 40., 70.])

In [51]:
#matrix multiplication
#element-wise
tensor_DJNew=torch.rand_like(tensor_DJ,dtype=torch.float32)
print(tensor_DJNew)
elemMul = tensor_DJ*tensor_DJNew
elemMul

tensor([0.7871, 0.4100, 0.2248])


tensor([0.7871, 1.6400, 1.5735])

In [53]:
matrixmul=torch.matmul(tensor_DJNew, tensor_DJ)
matrixmul

tensor(4.0007)