<a href="https://colab.research.google.com/github/DebjitHore/PyTorchLearning/blob/main/00_PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Useful Links:**

1. Deep Learning Book By Goodfellow :https://www.deeplearningbook.org/
2. Github link to repo : https://github.com/DebjitHore/PyTorchLearning
3. Alena Kruchkova YT DL Book Club: https://www.youtube.com/channel/UCF9O8Vj-FEbRDA5DcDGz-Pg/videos
4. learnpytorch.io
5. pytorch.org

1. Supervised Learning - Labelled data.
2. Unsupervised & Self-supervised Learning - Unlabelled data.
3. Transfer Learning - Pre-trained models on a separate data.
4. Reinforcement Learning - Check it out.

**Use-cases for Deep Learning**

1. Video recommendations
2. Language translation (sequence to sequence, seq2seq)
3. Speech recognition (sequence to sequence, seq2seq)
4. Computer vision, object detection (Classification/Regression)
5. Natural language processing (NLP)(Classification/Regression)


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


###Intro to Tensors

In [4]:
#scalar
sc=torch.tensor(7) #create tensors in PyTorch
sc

tensor(7)

In [5]:
sc.ndim

0

In [6]:
sc.item() #Get 0 dim-tensor back as python integer

7

In [7]:
vc= torch.tensor([7,7]) #1 dimensional tensor
vc

tensor([7, 7])

In [8]:
vc.ndim, vc.shape

(1, torch.Size([2]))

In [9]:
#2-d tensor aka matrix
mt= torch.tensor([[1,2,3],
                 [4,5,6]])
mt


tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
mt.ndim

2

In [11]:
mt[0], mt[1], mt.shape

(tensor([1, 2, 3]), tensor([4, 5, 6]), torch.Size([2, 3]))

###Creating random tensors

In [12]:
random= torch.rand(2,2,3)
print(random.type)
print(random)

<built-in method type of Tensor object at 0x7fd5d4c0c360>
tensor([[[0.2706, 0.0450, 0.2782],
         [0.3500, 0.8179, 0.2644]],

        [[0.2385, 0.4789, 0.8673],
         [0.4293, 0.5535, 0.2207]]])


**Zeros and Ones Tensors**

In [13]:
X=torch.zeros(2,2,3)
Y=torch.ones(2,2,3)
print(X), print(Y)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


(None, None)

In [14]:
Y_new=torch.rand_like(Y) #generate a tensor that is dimensionally same as Y, but with random numbers
print(Y_new)

tensor([[[0.9370, 0.0583, 0.9609],
         [0.3932, 0.1303, 0.0219]],

        [[0.4912, 0.5218, 0.3675],
         [0.9204, 0.8982, 0.6850]]])


In [15]:
#random image sized tensor
random_image_size_tensor=  torch.rand(224,224,3) #height, width of pixels and colour channels (R,G,B)

In [16]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [17]:
random_image_size_tensor.dtype

torch.float32

In [18]:
rangedTensor=torch.arange(start=1, end=1000, step=20.5)
rangedTensor

tensor([  1.0000,  21.5000,  42.0000,  62.5000,  83.0000, 103.5000, 124.0000,
        144.5000, 165.0000, 185.5000, 206.0000, 226.5000, 247.0000, 267.5000,
        288.0000, 308.5000, 329.0000, 349.5000, 370.0000, 390.5000, 411.0000,
        431.5000, 452.0000, 472.5000, 493.0000, 513.5000, 534.0000, 554.5000,
        575.0000, 595.5000, 616.0000, 636.5000, 657.0000, 677.5000, 698.0000,
        718.5000, 739.0000, 759.5000, 780.0000, 800.5000, 821.0000, 841.5000,
        862.0000, 882.5000, 903.0000, 923.5000, 944.0000, 964.5000, 985.0000])

In [19]:
rangedZeroTensor=torch.rand_like(rangedTensor) #random tensor same size as rangedTensor
rangedZeroTensor

tensor([0.9950, 0.8742, 0.0611, 0.8260, 0.5480, 0.4142, 0.5912, 0.7246, 0.4220,
        0.1801, 0.4569, 0.4099, 0.5037, 0.4485, 0.2063, 0.1733, 0.3081, 0.3615,
        0.6083, 0.6020, 0.9480, 0.9666, 0.8699, 0.5184, 0.3151, 0.9250, 0.6251,
        0.7311, 0.9451, 0.9212, 0.6110, 0.0471, 0.5715, 0.9191, 0.0850, 0.4672,
        0.2081, 0.0721, 0.8769, 0.9589, 0.8037, 0.5812, 0.9912, 0.6877, 0.7560,
        0.2946, 0.7788, 0.3314, 0.8326])

### Tensor Datatypes

In [20]:
rand_tensor= torch.rand_like(rangedZeroTensor, dtype=None, device=None,requires_grad=False)
#dtype is float32 by default, single precision
#device= whether the tensor lives on cpu or gpu
#requires_grad= tracks gradient

In [21]:
rand_tensor

tensor([0.9853, 0.9461, 0.5380, 0.6513, 0.0377, 0.0426, 0.3431, 0.0912, 0.8065,
        0.5483, 0.1176, 0.6050, 0.0793, 0.7432, 0.5532, 0.1851, 0.8617, 0.2600,
        0.7776, 0.0843, 0.4454, 0.9527, 0.5995, 0.8128, 0.1728, 0.2940, 0.8959,
        0.9855, 0.1001, 0.8342, 0.3265, 0.6808, 0.1221, 0.8417, 0.5023, 0.0532,
        0.1461, 0.3901, 0.1040, 0.5651, 0.6238, 0.6235, 0.0301, 0.2852, 0.7868,
        0.2621, 0.5285, 0.6934, 0.0135])

**Tensors need to have compatible data type, shape and device to be operable**
1. Device type refers to the location of the tensor, whether it lives on cpu or gpu (device="cuda")

### Getting tensor attributes & tensor operations

1. Attributes\
  &emsp; tensorName.dtype \
  &emsp; tensorName.shape \
  &emsp; tensorName.size() \
  &emsp; tensorName.device \


2. Tensor operations \
&emsp; Addition \
&emsp; Substraction \
&emsp; Multiplication (element-wise) \
&emsp; Division \
&emsp; Matrix multiplication \


In [22]:
tensor_DJ= torch.arange(start=1, end=9, step=3, dtype=torch.float32)
tensor_DJ, tensor_DJ.dtype

(tensor([1., 4., 7.]), torch.float32)

In [23]:
tensor_DJ+10

tensor([11., 14., 17.])

In [24]:
tensor_DJ*10

tensor([10., 40., 70.])

In [25]:
tensor_DJ-10

tensor([-9., -6., -3.])

In [26]:
torch.mul(tensor_DJ,10) #pytorch operator for element-wise matrix multiplication

tensor([10., 40., 70.])

In [27]:
#matrix multiplication
#element-wise
tensor_DJNew=torch.rand_like(tensor_DJ,dtype=torch.float32)
print(tensor_DJNew)
elemMul = tensor_DJ*tensor_DJNew
elemMul

tensor([0.4663, 0.5335, 0.2278])


tensor([0.4663, 2.1340, 1.5946])

In [28]:
matrixmul=torch.matmul(tensor_DJNew, tensor_DJ)
matrixmul

tensor(4.1950)

Rules for matrix mutliplication:

1. **Inner dimensions** must match:\
&emsp; (3,2) @ (3,2) won't work \
&emsp; (2,3) @ (3,2) will work
2. **Outer dimensions** will be the shape of resulting matrix



### Errors in deep learning : shape error for tensors

In [29]:
torch.mm (torch.rand(2,3), torch.rand(3,2)) #mm is an alias for matmul

tensor([[0.9257, 0.8713],
        [0.4697, 1.0832]])

### Transposing a tensor

In [30]:
#transpose of a tensor
B=torch.rand(3,4)
B, B.shape

(tensor([[0.4036, 0.3197, 0.8852, 0.4856],
         [0.6827, 0.5266, 0.1152, 0.4593],
         [0.4488, 0.1026, 0.9490, 0.3858]]),
 torch.Size([3, 4]))

In [31]:
A=B.T
A, A.shape

(tensor([[0.4036, 0.6827, 0.4488],
         [0.3197, 0.5266, 0.1026],
         [0.8852, 0.1152, 0.9490],
         [0.4856, 0.4593, 0.3858]]),
 torch.Size([4, 3]))

### Tensor aggregation

`Finding the min, max, sum etc `

In [32]:
x=torch.arange(1,101,10, dtype=torch.float32)
x

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [33]:
torch.min(x), x.min()

(tensor(1.), tensor(1.))

In [34]:
torch.max(x), x.max()

(tensor(91.), tensor(91.))

`torch.mean(x) needs float32 type`

In [35]:
torch.mean(x), x.mean()

(tensor(46.), tensor(46.))

In [36]:
torch.sum(x), x.sum()

(tensor(460.), tensor(460.))

`Finding the positional min and max`

In [37]:
x.argmin() #position of minimum value in tensor x

tensor(0)

In [38]:
x.argmax()

tensor(9)

### `Reshaping and stacking tensors` \
1. `Reshaping` - reshapes input tensor to defined shape
2. `View` - Return a view of input tensor of certain shape but keep same memory as parent tensor
3. `Stack` - combine tensors on top of each other (vstack) or side by side (hstack)
4. `Squeeze` - remove all '1' dimensions from a tensor
5. `Unsqueeze` - adds a '1' dimensions to target tensor
6. `Permute` - Return a view of input tensor with dimensions swapped in a certain way

In [39]:
import torch as t
x=t.arange(0,10)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [40]:
#reshape
#x_reshaped = x.reshape(1,10)
#x_reshaped = x.reshape(10,1)
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]))

`x` and `z` share the same memory location therefore any change made to `z` will reflect in `x`

In [41]:
#change the view
z= x.view(10,1)
z, z.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [42]:
#stacking
x_stacked = t.stack((x,x,x,x), dim=0) #vertical stacking
print(x_stacked, x_stacked.shape)
x_stacked_horizontal = t.stack((x,x,x,x), dim=1)
print(x_stacked_horizontal, x_stacked_horizontal.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([4, 10])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]]) torch.Size([10, 4])


In [43]:
#squeezing and unsqueezing
x_reshaped_new=x.reshape(1,10)
x_reshaped_new,x_reshaped_new.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [44]:
x_reshaped_new.squeeze(), x_reshaped_new.squeeze().shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [45]:
x_reshaped_new.unsqueeze(dim=1), x_reshaped_new.unsqueeze(dim=1).shape

(tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 10]))

`permuting`

In [46]:
y=t.rand(2,3,3)
print(y, y.shape)
y_p=t.permute(y,(2,1,0))
print(y_p, y_p.shape)


tensor([[[0.2216, 0.9866, 0.7357],
         [0.9036, 0.7232, 0.9384],
         [0.7321, 0.6510, 0.2835]],

        [[0.5926, 0.5599, 0.1423],
         [0.0376, 0.2195, 0.7285],
         [0.5869, 0.1856, 0.1303]]]) torch.Size([2, 3, 3])
tensor([[[0.2216, 0.5926],
         [0.9036, 0.0376],
         [0.7321, 0.5869]],

        [[0.9866, 0.5599],
         [0.7232, 0.2195],
         [0.6510, 0.1856]],

        [[0.7357, 0.1423],
         [0.9384, 0.7285],
         [0.2835, 0.1303]]]) torch.Size([3, 3, 2])


### `Indexing` -  Selecting data from Tensor

In [47]:
z=t.arange(1,19).reshape(2,3,3)
z, z.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [48]:
z[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
z[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [50]:
z[0, 0], z[0, 0:2]

(tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

`semi-colon` get all values

In [51]:
z[:,:,2]

tensor([[ 3,  6,  9],
        [12, 15, 18]])

### `PyTorch and NumPy`

* Data in NumPy, want in PyTorch Tensor - > `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> torch.Tensor.numpy()


In [54]:
import torch as t
import numpy as np

array = np.arange(1.0,8.0)
tensor = t.from_numpy(array) #warning when converting from numpy to pytorch tensor it reflects numpy's default dtype aka float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [53]:
array.dtype

dtype('float64')

In [58]:
#tensor to numpy array
tensor=t.randn(2,3,4)
array = t.Tensor.numpy(tensor)
array, tensor

(array([[[-1.2185278 , -0.3161683 ,  0.85601634, -0.7862942 ],
         [-1.0329304 ,  0.707968  , -0.16487926,  1.7753825 ],
         [ 0.7552598 , -0.9864068 ,  1.3533267 , -0.08452999]],
 
        [[-1.415083  ,  0.27361047, -1.2171167 , -0.06745192],
         [ 0.773643  ,  1.5380013 , -1.1887109 , -0.9626719 ],
         [ 0.76485187, -1.120306  ,  0.5551124 , -1.4531834 ]]],
       dtype=float32),
 tensor([[[-1.2185, -0.3162,  0.8560, -0.7863],
          [-1.0329,  0.7080, -0.1649,  1.7754],
          [ 0.7553, -0.9864,  1.3533, -0.0845]],
 
         [[-1.4151,  0.2736, -1.2171, -0.0675],
          [ 0.7736,  1.5380, -1.1887, -0.9627],
          [ 0.7649, -1.1203,  0.5551, -1.4532]]]))

In [63]:
array = np.random.rand(2,3,4)
tensor=t.from_numpy(array).type(t.float32) #typecasting the float64 numpy array to float32 which is default for pytorch
tensor, tensor.dtype

(tensor([[[0.9220, 0.2149, 0.9171, 0.1213],
          [0.7032, 0.3400, 0.2414, 0.4496],
          [0.4611, 0.6992, 0.8499, 0.6067]],
 
         [[0.8337, 0.0485, 0.3669, 0.9449],
          [0.9569, 0.2505, 0.6164, 0.7250],
          [0.6744, 0.6863, 0.3615, 0.8536]]]),
 torch.float32)

`Reproducibility in PyTorch code`

* Use of seed to reduce the randomness

In [65]:
randomSeed = 42 
t.manual_seed(randomSeed) #use everytime before creating random tensors 

### `Running tensors and PyTorch objects on the GPUs`



In [66]:
t.cuda.is_available()

False

In [68]:
device ="cuda" if t.cuda.is_available() else "cpu" #this code block should show GPU when running on colab with GPU on
device

'cpu'

`tensor.to(device) where device is set to "cuda" if available moves a tensor in cpu to gpu` \
`tensor.cpu() moves a tensor from "cuda" to "cpu" if it is by default created in gpu`